import 'package:flutter/material.dart';
import '../../data/models/product_cart_model.dart';
import '../../data/services/cart_service.dart';

class CartProvider with ChangeNotifier {
  final CartService _cartService = CartService();
  
  List<ProductCartModel> _cartItems = [];
  bool _isLoading = false;
  String _error = '';
  double _total = 0;

  List<ProductCartModel> get cartItems => _cartItems;
  bool get isLoading => _isLoading;
  String get error => _error;
  double get total => _total;
  double get totalPrice => _total;
  int get itemCount => _cartItems.length;

  // Load cart items
  void loadCartItems(String userId) {
    _isLoading = true;
    notifyListeners();

    _cartService.getCartItems(userId).listen(
      (items) {
        _cartItems = items;
        _calculateTotal();
        _isLoading = false;
        _error = '';
        notifyListeners();
      },
      onError: (error) {
        _error = error.toString();
        _isLoading = false;
        notifyListeners();
      },
    );
  }

  // Calculate total
  void _calculateTotal() {
    _total = _cartItems.fold(0, (sum, item) => sum + item.totalPrice);
  }

  // Add to cart with detailed parameters
  Future<bool> addToCart({
    required String userId,
    required String menuItemId,
    required String menuItemName,
    required String menuItemPhoto,
    required double price,
    required int quantity,
    double additionalPrice = 0.0,
    String? observation,
    List<String>? additionals,
  }) async {
    final cartItem = ProductCartModel(
      id: '', // Will be generated by Firestore
      userId: userId,
      menuItemId: menuItemId,
      menuItemName: menuItemName,
      menuItemPhoto: menuItemPhoto,
      quantity: quantity,
      price: price,
      additionalPrice: additionalPrice,
      observation: observation,
      additionals: additionals ?? [],
      createdAt: DateTime.now(),
    );
    final id = await _cartService.addToCart(cartItem);
    return id != null;
  }

  // Add to cart with model
  Future<bool> addToCartModel(ProductCartModel cartItem) async {
    final id = await _cartService.addToCart(cartItem);
    return id != null;
  }

  // Update quantity
  Future<bool> updateQuantity(String id, int quantity) async {
    if (quantity <= 0) {
      return await removeFromCart(id);
    }
    return await _cartService.updateCartItemQuantity(id, quantity);
  }

  // Remove from cart
  Future<bool> removeFromCart(String id) async {
    return await _cartService.removeFromCart(id);
  }

  // Clear cart
  Future<bool> clearCart(String userId) async {
    return await _cartService.clearCart(userId);
  }
}
